# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "2dglOvUNDBDphTqjF3R24LYYMl8H9aLDG+ayTzm3XgvVS1G9De5T7lY9lkbpw0f0v2KIWxoT8ftcRO0vCq/OziTAuIYx1zyu5YMImry/IWhPoPVvg9hjqAVax0fnOZWG6HBJWZY/0Q81JrpHjcarWcWUPTlnOerd/8wo2nIExJ0+s5M1gceDblDTnzaN0tYpDu/ikz3iaLCYGIts8JMii9IKi5ikVCN1dale1OjcEAm/fmkfDaDQBiBR3aBL3ZOPUlNC97hkhcdKYufR4iowcSTGkSIp+FSn5sPGfLnsmdvqn38F9ENZk9ThqFO0BFcHF4bBBNp/2027U7pelEMpD0fOfoYS8RYwDZEpfxzLI7kSreuvaDPjVHUOf9tcdmoA+a4N5RRR4BCYwfBOAQ7LlUzp10Ij5kYqUaCnm0yZPiwcrQwXTaB89A65d5c9OlXD8CjKtIagK4aqgYe/m0y23dimiI0B2Pl4ej+rZ4EDbPugtEeFv+TqMaRWzBA64ZdEglDumH1ijV3N9SJIWO62pz90vf+M+aVQPejJKVljWhxmnzLKkSav08q2NkwjQDqmZJO4H5eYYbWMlmKxCHcPZy9KplSXXj68isWnFDeW3T++nTYJEiTdr6bhPRTVoiu/QQOWiEtIF3ziTKQ7K3o0mghKH3akLAa/YHYm+S3sdR0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
