travis:
  secure:
    BINSTAR_TOKEN: Sq+TL7DDDeSVubR3keQMwK2KKz9RrQkJfglrveUCHJPUh5dWqQ1Vk8zjxhqlEtstm6koLlGcyWc/q/mJgV4oWyBmJQQ9nXwESLfAKObunmzP7rLSrM1xkwiaWXHKTv9HIUfHr1G7DQ5GT6FM4IrZWse+gl9bovk+Vy6vUkEV0BGpcnK6kgMtrn57FPUr0qHZrghp2NCJmuM4Q/WGGn3cLUBPu+MDY3H0xzRVWpHed03U94VWm5nduGhmg/90pEH5x8oXSf0ocpIP5Q7G9iNqCeB+t8aAq0ZPN9cuEXY09YLSHNUfj8XSWP5mlbzo5nwmvlFL+9YW7MZxjHwC/HBVgnNtYxd8AFcx+gx4Ll9dAfiJBIf0vjQbYD24vfquBVYIy0/ljWs9eXHJJdBxEO7VC1Pu5lhGvADmbs8W/orVCEDSNScOSwJfs+HUEpUJIr8ml1tFgvAlVeofLJufoeAp5FHRUB0QAko6IZxMxzJbJRzLa9k0wofpiuYDd5IfX6Cb0EB2w71eVY0TMkL4JCoM2Ca/+AC3fIfl7RQ61MnEn2cv+/PYAdlijoZJhNgZW8wYiBPZrV+EVEN/9J/RRm5sCKz0aHMqDAmWhZckdlPFw43aZMrXCkKFJTqyCIM7jjA3N5SI501/6mlCTFgv5/gu1VFYPKByuGLVU6ZVb3wEJPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
