travis:
  secure:
    BINSTAR_TOKEN: gcybEl8Lit2BvijeUpEuzB4fcucGrIcXbsgvhaB4geuHcnZTrt4yjh/VQfump/3xwAxyY26bBYVCQKVbRCiBj/nIWO3BWVFT0wynmynn7UBteQx07tSLghG/+RCJzUsN8KDL/tB/2emvn8aB0iVGwaHWG02dchRS7jCS1Ah053r5ykYEI3UK29K+jeHyNT2OtQJiSAvrjaeAgMvbqGamXzNF1hwn00kv9LuBSI+t3g/kDPZ6kW9U2hfYhaOZP8xSfIPPAuN2xXQPLORXZSSn5vGBDuPKLlp+Y7Ap/BQmPlNvZaNN9qpLDT+1O/QAfxAZ6dlNPiWLVS40BnCOtDxS9jgud/fz9/YCX6uZ+6s9fzcmd2MfP4gD2blXZTCYiv6dMCb5rFG9QEg9+TYBBPxXM+Q6EWDzIbqlqA2MN5NnjO4E78P8MNS417MKfp3NtDNGO7PTNeg9PsOqi4gKdNolUjQONDRmzZj3uVe+X/dO05jQ2yX4uN+9R2+CHldugAxLMD2pgJU6M7ncxVIhuehalsQ+Beixle77bcwvaonG91l6Cq6QZwi39rX41h/ATzPPXgiczXMKH09hhntfdSKSmUGkmk80tuAEnviFrRPm4ffumnKrbjgWHFpNv9ZeeHQ8PQj4qFMhyQoxJjFsSR9/Drp65zPjgmLWHRkmk4mclpk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
