travis:
  secure:
    BINSTAR_TOKEN: d01QBgG9yYpjMjpuICoyb7LIgqDgMpWHwumoIPJoXhMlDUadHlmLp80xgMr+e6IDEjOw55dbs1TfZMP0/JpYzxv2vRWcjJ0cBrva/ddDTXnCFelG9D2QfNf3zJMp03cbD6v2HNBuEb2WvAkzCO4kEs5evrsi5Kre2NhDCgEQsYsnZUXS8jpDWP8lkPT1B1ZZEmQDEQxaql+gwUHiN67ExvIZDaI9vvDx/R9yTC99N5km+qaJZFa+VW30hmtbh56J2DUAS89akFbVno7pxAmuIfcAgJ9x0zx1AYa1p+pBpEKR3JVMTXBm1HOJ9UIsNNYN9BuZWYIc85sWGKh7cBN8rNnJLH03U54hMs2SjhmigevNu1iBfWYWrQwBYf4sK/+HKzjNzkZW59J4xxoh1AMwznN+RduwDxettzb31QaSWpES25yX0TE/RT2e4mIuJwV1ssPTwcvs9Pf8ReP13mbLz0VAuyqrZBvpVAnmoI4Fe+9KxGKTUDy2Rqyy5UyogkcYyxUwmUAzIDOAJ8sxvDTz1VjLXY6os2qHzmpwHmjciv8wdf8yriqcEJQkMEMt4v+IbcbT99NWljoerXEPzSOrnuOmJxCKrEAWF5dKFbFztR31tifdyDzoqnoSgRUuPEgDFa2jnFdQyyWmEUizNLit2Zq+AOzzZhP0TNk+JBsuab4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
